# See the documentation for more information
# on what each of these do

# Dimensions of screen in characters
screen_width: 115
screen_height: 40

# Dimensions of map in characters
map_width: 99
map_height: 49

# Height of console
console_height: 10

# Width of right panel
panel_width: 25

# Fullscreen mode
fullscreen: false

# Path to desired font
fontpath: "fonts/terminal8x14_gs_ro.png"

# Font type. Default: Default
# Options:
# * Default
# * Greyscale
fonttype: "Greyscale"

# Font layout. Default: Tcod
# Options:
# * Tcod
# * AsciiInRow
# * AsciiInCol
fontlayout: "AsciiInRow"

# Desired renderer. Default: SDL
# Options:
# * SDL
# * GLSL
# * OpenGL
renderer: "SDL"

# Wizard mode
wizard: true

# Enable/disable debug logs
debug: true